package machine;
public enum IssueKind
{
    BAD_EMISSIONS,
    DEPENDENCY_CYCLE,
    FL_NAME_BAD,
    FL_NAME_BAD_MACHINE,
    FL_NAME_CONFLICTS,
    INITIAL_MISSING,
    INITIAL_VIRTUAL,
    NAME_CONFLICTS,
    OVERLAPPING_EMIT,
    OVERLAPPING_GOTO,
    RESET_MISSING,
    SPECIAL_SIGNAL_WRONG_KIND,
    UNCOMPILED,
    VIRTUAL_NO_GOTO,
    VIRTUAL_STATE_CYCLE;
}
